"""
A3. Canonical Asset Universe using CoinGecko IDs.
Version: BR1-BREADTH-UNIVERSE-v1
"""

BR1_BREADTH_UNIVERSE_V1 = [
    {"id": "bitcoin", "symbol": "BTC", "name": "Bitcoin"},
    {"id": "ethereum", "symbol": "ETH", "name": "Ethereum"},
    {"id": "binancecoin", "symbol": "BNB", "name": "BNB"},
    {"id": "solana", "symbol": "SOL", "name": "Solana"},
    {"id": "ripple", "symbol": "XRP", "name": "XRP"},
    {"id": "dogecoin", "symbol": "DOGE", "name": "Dogecoin"},
    {"id": "the-open-network", "symbol": "TON", "name": "Toncoin"},
    {"id": "cardano", "symbol": "ADA", "name": "Cardano"},
    {"id": "shiba-inu", "symbol": "SHIB", "name": "Shiba Inu"},
    {"id": "avalanche-2", "symbol": "AVAX", "name": "Avalanche"},
    {"id": "tron", "symbol": "TRX", "name": "TRON"},
    {"id": "polkadot", "symbol": "DOT", "name": "Polkadot"},
    {"id": "bitcoin-cash", "symbol": "BCH", "name": "Bitcoin Cash"},
    {"id": "chainlink", "symbol": "LINK", "name": "Chainlink"},
    {"id": "polygon-ecosystem-token", "symbol": "POL", "name": "Polygon (formerly MATIC)"},
    {"id": "near", "symbol": "NEAR", "name": "NEAR Protocol"},
    {"id": "litecoin", "symbol": "LTC", "name": "Litecoin"},
    {"id": "internet-computer", "symbol": "ICP", "name": "Internet Computer"},
    {"id": "leo-token", "symbol": "LEO", "name": "UNUS SED LEO"},
    {"id": "fetch-ai", "symbol": "FET", "name": "Artificial Superintelligence Alliance"},
    {"id": "pepe", "symbol": "PEPE", "name": "Pepe"},
    {"id": "stellar", "symbol": "XLM", "name": "Stellar"},
    {"id": "aptos", "symbol": "APT", "name": "Aptos"},
    {"id": "blockstack", "symbol": "STX", "name": "Stacks"},
    {"id": "uniswap", "symbol": "UNI", "name": "Uniswap"},
    {"id": "monero", "symbol": "XMR", "name": "Monero"},
    {"id": "mantle", "symbol": "MNT", "name": "Mantle"},
    {"id": "ethereum-classic", "symbol": "ETC", "name": "Ethereum Classic"},
    {"id": "render-token", "symbol": "RENDER", "name": "Render"},
    {"id": "injective-protocol", "symbol": "INJ", "name": "Injective"},
    {"id": "arweave", "symbol": "AR", "name": "Arweave"},
    {"id": "filecoin", "symbol": "FIL", "name": "Filecoin"},
    {"id": "cosmos", "symbol": "ATOM", "name": "Cosmos Hub"},
    {"id": "immutable-x", "symbol": "IMX", "name": "Immutable"},
    {"id": "maker", "symbol": "MKR", "name": "Maker"},
    {"id": "vechain", "symbol": "VET", "name": "VeChain"},
    {"id": "optimism", "symbol": "OP", "name": "Optimism"},
    {"id": "the-graph", "symbol": "GRT", "name": "The Graph"},
    {"id": "bittensor", "symbol": "TAO", "name": "Bittensor"},
    {"id": "sui", "symbol": "SUI", "name": "Sui"},
    {"id": "dogwifcoin", "symbol": "WIF", "name": "dogwifhat"},
    {"id": "floki", "symbol": "FLOKI", "name": "FLOKI"},
    {"id": "theta-token", "symbol": "THETA", "name": "Theta Network"},
    {"id": "aave", "symbol": "AAVE", "name": "Aave"},
    {"id": "celestia", "symbol": "TIA", "name": "Celestia"},
    {"id": "fantom", "symbol": "FTM", "name": "Fantom"},
    {"id": "thorchain", "symbol": "RUNE", "name": "THORChain"},
    {"id": "algorand", "symbol": "ALGO", "name": "Algorand"},
    {"id": "lido-dao", "symbol": "LDO", "name": "Lido DAO"},
    {"id": "sei-network", "symbol": "SEI", "name": "Sei"}
]
