"""postgresql_foundation

Revision ID: 0001
Revises:
Create Date: 2026-08-21 00:06:20.740777
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('canonical_id', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('metadata_id', sa.String(length=100), nullable=True),
    sa.Column('legacy_identity', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE','INACTIVE')", name=op.f('ck_assets_status')),
    sa.PrimaryKeyConstraint('asset_id', name=op.f('pk_assets')),
    sa.UniqueConstraint('canonical_id', name=op.f('uq_assets_canonical_id')),
    sa.UniqueConstraint('symbol', name=op.f('uq_assets_symbol')),
    schema='breadth_v2'
    )
    op.create_table('data_sources',
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('venue', sa.String(length=100), nullable=False),
    sa.Column('market_type', sa.String(length=16), nullable=False),
    sa.Column('api_base_url', sa.Text(), nullable=False),
    sa.Column('terms_url', sa.Text(), nullable=False),
    sa.Column('terms_review_status', sa.String(length=16), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("market_type IN ('SPOT')", name=op.f('ck_data_sources_market_type')),
    sa.CheckConstraint("terms_review_status IN ('PENDING','ACCEPTED','REJECTED')", name=op.f('ck_data_sources_terms_review_status')),
    sa.PrimaryKeyConstraint('source_id', name=op.f('pk_data_sources')),
    schema='breadth_v2'
    )
    op.create_table('source_policy_versions',
    sa.Column('source_policy_version', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('definition_hash', sa.String(length=64), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','ACTIVE','RETIRED')", name=op.f('ck_source_policy_versions_status')),
    sa.PrimaryKeyConstraint('source_policy_version', name=op.f('pk_source_policy_versions')),
    schema='breadth_v2'
    )
    op.create_table('universe_versions',
    sa.Column('universe_version', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('series_kind', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('inception_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_size', sa.Integer(), nullable=False),
    sa.Column('definition_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("series_kind IN ('LIVE','RESEARCH')", name=op.f('ck_universe_versions_series_kind')),
    sa.CheckConstraint("status IN ('DRAFT','ACTIVE','RETIRED')", name=op.f('ck_universe_versions_status')),
    sa.CheckConstraint('expected_size > 0', name=op.f('ck_universe_versions_expected_size')),
    sa.PrimaryKeyConstraint('universe_version', name=op.f('pk_universe_versions')),
    schema='breadth_v2'
    )
    op.create_table('provider_mappings',
    sa.Column('mapping_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('provider_asset_id', sa.String(length=100), nullable=False),
    sa.Column('base_code', sa.String(length=32), nullable=False),
    sa.Column('quote_code', sa.String(length=32), nullable=False),
    sa.Column('instrument_id', sa.String(length=100), nullable=False),
    sa.Column('mapping_version', sa.String(length=64), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE','DELISTED','DISABLED')", name=op.f('ck_provider_mappings_status')),
    sa.CheckConstraint('valid_to IS NULL OR valid_to > valid_from', name=op.f('ck_provider_mappings_valid_range')),
    sa.ForeignKeyConstraint(['asset_id'], ['breadth_v2.assets.asset_id'], name=op.f('fk_provider_mappings_asset_id_assets')),
    sa.ForeignKeyConstraint(['source_id'], ['breadth_v2.data_sources.source_id'], name=op.f('fk_provider_mappings_source_id_data_sources')),
    sa.PrimaryKeyConstraint('mapping_id', name=op.f('pk_provider_mappings')),
    sa.UniqueConstraint('mapping_id', 'asset_id', 'source_id', name='uq_provider_mapping_asset_source'),
    sa.UniqueConstraint('mapping_id', 'asset_id', name='uq_provider_mapping_asset'),
    sa.UniqueConstraint('source_id', 'instrument_id', 'mapping_version', name=op.f('uq_provider_mappings_source_id')),
    schema='breadth_v2'
    )
    op.create_table('series_definitions',
    sa.Column('series_version', sa.String(length=120), nullable=False),
    sa.Column('series_kind', sa.String(length=16), nullable=False),
    sa.Column('universe_version', sa.String(length=100), nullable=False),
    sa.Column('source_policy_version', sa.String(length=100), nullable=False),
    sa.Column('formula_version', sa.String(length=100), nullable=False),
    sa.Column('normalizer_version', sa.String(length=100), nullable=False),
    sa.Column('methodology_version', sa.String(length=100), nullable=False),
    sa.Column('inception_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('definition_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("series_kind <> 'LIVE' OR inception_at IS NOT NULL", name=op.f('ck_series_definitions_live_requires_inception')),
    sa.CheckConstraint("series_kind IN ('LIVE','RESEARCH')", name=op.f('ck_series_definitions_series_kind')),
    sa.CheckConstraint("status IN ('CANDIDATE','ACTIVE','RETIRED')", name=op.f('ck_series_definitions_status')),
    sa.ForeignKeyConstraint(['source_policy_version'], ['breadth_v2.source_policy_versions.source_policy_version'], name=op.f('fk_series_definitions_source_policy_version_source_policy_versions')),
    sa.ForeignKeyConstraint(['universe_version'], ['breadth_v2.universe_versions.universe_version'], name=op.f('fk_series_definitions_universe_version_universe_versions')),
    sa.PrimaryKeyConstraint('series_version', name=op.f('pk_series_definitions')),
    schema='breadth_v2'
    )
    op.create_table('source_versions',
    sa.Column('source_version_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('adapter_version', sa.String(length=64), nullable=False),
    sa.Column('api_contract_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('api_schema_hash', sa.String(length=64), nullable=False),
    sa.Column('archive_release', sa.String(length=100), nullable=False),
    sa.Column('archive_checksum', sa.String(length=64), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['breadth_v2.data_sources.source_id'], name=op.f('fk_source_versions_source_id_data_sources')),
    sa.PrimaryKeyConstraint('source_version_id', name=op.f('pk_source_versions')),
    sa.UniqueConstraint('source_version_id', 'source_id', name='uq_source_version_source'),
    sa.UniqueConstraint('source_id', 'adapter_version', 'api_schema_hash', 'archive_release', name=op.f('uq_source_versions_source_id')),
    schema='breadth_v2'
    )
    op.create_table('universe_memberships',
    sa.Column('universe_version', sa.String(length=100), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('included_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('included_to', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('included_to IS NULL OR included_to > included_from', name=op.f('ck_universe_memberships_included_range')),
    sa.CheckConstraint('ordinal > 0', name=op.f('ck_universe_memberships_positive_ordinal')),
    sa.ForeignKeyConstraint(['asset_id'], ['breadth_v2.assets.asset_id'], name=op.f('fk_universe_memberships_asset_id_assets')),
    sa.ForeignKeyConstraint(['universe_version'], ['breadth_v2.universe_versions.universe_version'], name=op.f('fk_universe_memberships_universe_version_universe_versions')),
    sa.PrimaryKeyConstraint('universe_version', 'asset_id', name=op.f('pk_universe_memberships')),
    sa.UniqueConstraint('universe_version', 'ordinal', name=op.f('uq_universe_memberships_universe_version')),
    schema='breadth_v2'
    )
    op.create_table('ingestion_runs',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('run_type', sa.String(length=20), nullable=False),
    sa.Column('series_version', sa.String(length=120), nullable=True),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('timeframe', sa.String(length=4), nullable=True),
    sa.Column('target_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('expected_count', sa.Integer(), nullable=False),
    sa.Column('received_count', sa.Integer(), nullable=False),
    sa.Column('valid_count', sa.Integer(), nullable=False),
    sa.Column('quarantined_count', sa.Integer(), nullable=False),
    sa.Column('scheduler_id', sa.String(length=100), nullable=True),
    sa.Column('code_sha', sa.String(length=64), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("run_type IN ('BOOTSTRAP','INCREMENTAL','RECOMPUTE','REPAIR')", name=op.f('ck_ingestion_runs_run_type')),
    sa.CheckConstraint("status IN ('PENDING','RUNNING','SUCCEEDED','FAILED')", name=op.f('ck_ingestion_runs_status')),
    sa.CheckConstraint("timeframe IS NULL OR timeframe IN ('4h','1d','1w')", name=op.f('ck_ingestion_runs_timeframe')),
    sa.CheckConstraint('attempt > 0', name=op.f('ck_ingestion_runs_attempt')),
    sa.CheckConstraint('expected_count >= 0 AND received_count >= 0 AND valid_count >= 0 AND quarantined_count >= 0', name=op.f('ck_ingestion_runs_counts')),
    sa.CheckConstraint('valid_count + quarantined_count <= received_count', name=op.f('ck_ingestion_runs_classified_count')),
    sa.CheckConstraint("(status IN ('PENDING','RUNNING') AND finished_at IS NULL) OR (status IN ('SUCCEEDED','FAILED') AND finished_at IS NOT NULL)", name=op.f('ck_ingestion_runs_finished_status')),
    sa.CheckConstraint('target_end IS NULL OR target_start IS NULL OR target_end >= target_start', name=op.f('ck_ingestion_runs_target_range')),
    sa.ForeignKeyConstraint(['series_version'], ['breadth_v2.series_definitions.series_version'], name=op.f('fk_ingestion_runs_series_version_series_definitions')),
    sa.ForeignKeyConstraint(['source_id'], ['breadth_v2.data_sources.source_id'], name=op.f('fk_ingestion_runs_source_id_data_sources')),
    sa.PrimaryKeyConstraint('run_id', name=op.f('pk_ingestion_runs')),
    schema='breadth_v2'
    )
    op.create_table('source_policy_mappings',
    sa.Column('source_policy_version', sa.String(length=100), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('mapping_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['breadth_v2.assets.asset_id'], name=op.f('fk_source_policy_mappings_asset_id_assets')),
    sa.ForeignKeyConstraint(['mapping_id', 'asset_id'], ['breadth_v2.provider_mappings.mapping_id', 'breadth_v2.provider_mappings.asset_id'], name=op.f('fk_source_policy_mappings_mapping_id_provider_mappings')),
    sa.ForeignKeyConstraint(['source_policy_version'], ['breadth_v2.source_policy_versions.source_policy_version'], name=op.f('fk_source_policy_mappings_source_policy_version_source_policy_versions')),
    sa.PrimaryKeyConstraint('source_policy_version', 'asset_id', name=op.f('pk_source_policy_mappings')),
    schema='breadth_v2'
    )
    op.create_table('timeframe_cohorts',
    sa.Column('series_version', sa.String(length=120), nullable=False),
    sa.Column('timeframe', sa.String(length=4), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('included_in_denominator', sa.Boolean(), nullable=False),
    sa.Column('history_count_at_inception', sa.Integer(), nullable=False),
    sa.Column('eligibility_reason', sa.String(length=100), nullable=False),
    sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("timeframe IN ('4h','1d','1w')", name=op.f('ck_timeframe_cohorts_timeframe')),
    sa.CheckConstraint('history_count_at_inception >= 0', name=op.f('ck_timeframe_cohorts_history_count')),
    sa.ForeignKeyConstraint(['asset_id'], ['breadth_v2.assets.asset_id'], name=op.f('fk_timeframe_cohorts_asset_id_assets')),
    sa.ForeignKeyConstraint(['series_version'], ['breadth_v2.series_definitions.series_version'], name=op.f('fk_timeframe_cohorts_series_version_series_definitions')),
    sa.PrimaryKeyConstraint('series_version', 'timeframe', 'asset_id', name=op.f('pk_timeframe_cohorts')),
    schema='breadth_v2'
    )
    op.create_table('breadth_snapshots',
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('series_version', sa.String(length=120), nullable=False),
    sa.Column('series_kind', sa.String(length=16), nullable=False),
    sa.Column('universe_version', sa.String(length=100), nullable=False),
    sa.Column('source_policy_version', sa.String(length=100), nullable=False),
    sa.Column('formula_version', sa.String(length=100), nullable=False),
    sa.Column('normalizer_version', sa.String(length=100), nullable=False),
    sa.Column('timeframe', sa.String(length=4), nullable=False),
    sa.Column('candle_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pct_above_ema20', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('pct_above_ema50', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('pct_above_ema200', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('breadth_score', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('numerator20', sa.Integer(), nullable=True),
    sa.Column('numerator50', sa.Integer(), nullable=True),
    sa.Column('numerator200', sa.Integer(), nullable=True),
    sa.Column('universe_size', sa.Integer(), nullable=False),
    sa.Column('cohort_size', sa.Integer(), nullable=False),
    sa.Column('structural_coverage', sa.Numeric(precision=9, scale=8), nullable=False),
    sa.Column('component_coverage', sa.Numeric(precision=9, scale=8), nullable=False),
    sa.Column('data_quality_score', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('data_quality_label', sa.String(length=20), nullable=False),
    sa.Column('btc_close', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('eth_close', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("(status = 'PUBLISHED' AND pct_above_ema20 IS NOT NULL AND pct_above_ema50 IS NOT NULL AND pct_above_ema200 IS NOT NULL AND breadth_score IS NOT NULL AND btc_close IS NOT NULL AND eth_close IS NOT NULL) OR (status <> 'PUBLISHED' AND pct_above_ema20 IS NULL AND pct_above_ema50 IS NULL AND pct_above_ema200 IS NULL AND breadth_score IS NULL)", name=op.f('ck_breadth_snapshots_atomic_components')),
    sa.CheckConstraint("data_quality_label IN ('HIGH','MEDIUM','LOW','UNAVAILABLE')", name=op.f('ck_breadth_snapshots_data_quality_label')),
    sa.CheckConstraint("series_kind IN ('LIVE','RESEARCH')", name=op.f('ck_breadth_snapshots_series_kind')),
    sa.CheckConstraint("status IN ('PUBLISHED','REJECTED','UNAVAILABLE')", name=op.f('ck_breadth_snapshots_status')),
    sa.CheckConstraint("timeframe IN ('4h','1d','1w')", name=op.f('ck_breadth_snapshots_timeframe')),
    sa.CheckConstraint('component_coverage >= 0 AND component_coverage <= 1', name=op.f('ck_breadth_snapshots_component_coverage')),
    sa.CheckConstraint('data_quality_score >= 0 AND data_quality_score <= 100', name=op.f('ck_breadth_snapshots_data_quality')),
    sa.CheckConstraint('structural_coverage >= 0 AND structural_coverage <= 1', name=op.f('ck_breadth_snapshots_structural_coverage')),
    sa.CheckConstraint('universe_size > 0 AND cohort_size > 0 AND cohort_size <= universe_size', name=op.f('ck_breadth_snapshots_sizes')),
    sa.ForeignKeyConstraint(['run_id'], ['breadth_v2.ingestion_runs.run_id'], name=op.f('fk_breadth_snapshots_run_id_ingestion_runs')),
    sa.ForeignKeyConstraint(['series_version'], ['breadth_v2.series_definitions.series_version'], name=op.f('fk_breadth_snapshots_series_version_series_definitions')),
    sa.ForeignKeyConstraint(['source_policy_version'], ['breadth_v2.source_policy_versions.source_policy_version'], name=op.f('fk_breadth_snapshots_source_policy_version_source_policy_versions')),
    sa.ForeignKeyConstraint(['universe_version'], ['breadth_v2.universe_versions.universe_version'], name=op.f('fk_breadth_snapshots_universe_version_universe_versions')),
    sa.PrimaryKeyConstraint('snapshot_id', name=op.f('pk_breadth_snapshots')),
    sa.UniqueConstraint('series_version', 'timeframe', 'candle_time', name=op.f('uq_breadth_snapshots_series_version')),
    schema='breadth_v2'
    )
    op.create_index('ix_breadth_snapshots_lookup', 'breadth_snapshots', ['series_version', 'timeframe', 'candle_time'], unique=False, schema='breadth_v2')
    op.create_table('canonical_candles',
    sa.Column('candle_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('mapping_id', sa.UUID(), nullable=False),
    sa.Column('source_version_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('normalizer_version', sa.String(length=100), nullable=False),
    sa.Column('timeframe', sa.String(length=4), nullable=False),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('close_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('high', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('low', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('close', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('base_volume', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('quote_volume', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('trade_count', sa.BigInteger(), nullable=True),
    sa.Column('provider_closed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_payload_hash', sa.String(length=64), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("(timeframe = '4h' AND close_time = open_time + INTERVAL '4 hours') OR (timeframe = '1d' AND close_time = open_time + INTERVAL '1 day') OR (timeframe = '1w' AND close_time = open_time + INTERVAL '7 days')", name=op.f('ck_canonical_candles_exact_duration')),
    sa.CheckConstraint("status IN ('VALID','QUARANTINED')", name=op.f('ck_canonical_candles_status')),
    sa.CheckConstraint("timeframe IN ('4h','1d','1w')", name=op.f('ck_canonical_candles_timeframe')),
    sa.CheckConstraint('base_volume IS NULL OR base_volume >= 0', name=op.f('ck_canonical_candles_base_volume')),
    sa.CheckConstraint('close_time > open_time', name=op.f('ck_canonical_candles_positive_duration')),
    sa.CheckConstraint('low <= open AND low <= close AND high >= open AND high >= close AND low <= high', name=op.f('ck_canonical_candles_ohlc_order')),
    sa.CheckConstraint('open > 0 AND high > 0 AND low > 0 AND close > 0', name=op.f('ck_canonical_candles_positive_ohlc')),
    sa.CheckConstraint('quote_volume IS NULL OR quote_volume >= 0', name=op.f('ck_canonical_candles_quote_volume')),
    sa.CheckConstraint('trade_count IS NULL OR trade_count >= 0', name=op.f('ck_canonical_candles_trade_count')),
    sa.ForeignKeyConstraint(['asset_id'], ['breadth_v2.assets.asset_id'], name=op.f('fk_canonical_candles_asset_id_assets')),
    sa.ForeignKeyConstraint(['mapping_id', 'asset_id', 'source_id'], ['breadth_v2.provider_mappings.mapping_id', 'breadth_v2.provider_mappings.asset_id', 'breadth_v2.provider_mappings.source_id'], name=op.f('fk_canonical_candles_mapping_id_provider_mappings')),
    sa.ForeignKeyConstraint(['run_id'], ['breadth_v2.ingestion_runs.run_id'], name=op.f('fk_canonical_candles_run_id_ingestion_runs')),
    sa.ForeignKeyConstraint(['source_version_id', 'source_id'], ['breadth_v2.source_versions.source_version_id', 'breadth_v2.source_versions.source_id'], name=op.f('fk_canonical_candles_source_version_id_source_versions')),
    sa.PrimaryKeyConstraint('candle_id', name=op.f('pk_canonical_candles')),
    sa.UniqueConstraint('mapping_id', 'timeframe', 'open_time', 'normalizer_version', name=op.f('uq_canonical_candles_mapping_id')),
    schema='breadth_v2'
    )
    op.create_index('ix_canonical_candles_asset_time', 'canonical_candles', ['asset_id', 'timeframe', 'open_time'], unique=False, schema='breadth_v2')
    op.create_table('ingestion_errors',
    sa.Column('error_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('mapping_id', sa.UUID(), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('timeframe', sa.String(length=4), nullable=True),
    sa.Column('candle_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=False),
    sa.Column('retryable', sa.Boolean(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("timeframe IS NULL OR timeframe IN ('4h','1d','1w')", name=op.f('ck_ingestion_errors_timeframe')),
    sa.ForeignKeyConstraint(['asset_id'], ['breadth_v2.assets.asset_id'], name=op.f('fk_ingestion_errors_asset_id_assets')),
    sa.ForeignKeyConstraint(['mapping_id'], ['breadth_v2.provider_mappings.mapping_id'], name=op.f('fk_ingestion_errors_mapping_id_provider_mappings')),
    sa.ForeignKeyConstraint(['run_id'], ['breadth_v2.ingestion_runs.run_id'], name=op.f('fk_ingestion_errors_run_id_ingestion_runs')),
    sa.ForeignKeyConstraint(['source_id'], ['breadth_v2.data_sources.source_id'], name=op.f('fk_ingestion_errors_source_id_data_sources')),
    sa.PrimaryKeyConstraint('error_id', name=op.f('pk_ingestion_errors')),
    schema='breadth_v2'
    )
    op.create_table('source_artifacts',
    sa.Column('artifact_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('source_version_id', sa.UUID(), nullable=False),
    sa.Column('artifact_type', sa.String(length=40), nullable=False),
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('range_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('range_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('range_end IS NULL OR range_start IS NULL OR range_end >= range_start', name=op.f('ck_source_artifacts_range')),
    sa.ForeignKeyConstraint(['run_id'], ['breadth_v2.ingestion_runs.run_id'], name=op.f('fk_source_artifacts_run_id_ingestion_runs')),
    sa.ForeignKeyConstraint(['source_version_id'], ['breadth_v2.source_versions.source_version_id'], name=op.f('fk_source_artifacts_source_version_id_source_versions')),
    sa.PrimaryKeyConstraint('artifact_id', name=op.f('pk_source_artifacts')),
    sa.UniqueConstraint('source_version_id', 'checksum', name=op.f('uq_source_artifacts_source_version_id')),
    schema='breadth_v2'
    )
    op.create_table('asset_indicators',
    sa.Column('series_version', sa.String(length=120), nullable=False),
    sa.Column('universe_version', sa.String(length=100), nullable=False),
    sa.Column('formula_version', sa.String(length=100), nullable=False),
    sa.Column('normalizer_version', sa.String(length=100), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('mapping_id', sa.UUID(), nullable=False),
    sa.Column('timeframe', sa.String(length=4), nullable=False),
    sa.Column('candle_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('candle_id', sa.UUID(), nullable=False),
    sa.Column('close', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('ema20', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('ema50', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('ema200', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('ema20_state', sa.String(length=16), nullable=False),
    sa.Column('ema50_state', sa.String(length=16), nullable=False),
    sa.Column('ema200_state', sa.String(length=16), nullable=False),
    sa.Column('consecutive_count', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("(ema200_state = 'AVAILABLE') = (ema200 IS NOT NULL)", name=op.f('ck_asset_indicators_ema200_value_state')),
    sa.CheckConstraint("(ema20_state = 'AVAILABLE') = (ema20 IS NOT NULL)", name=op.f('ck_asset_indicators_ema20_value_state')),
    sa.CheckConstraint("(ema50_state = 'AVAILABLE') = (ema50 IS NOT NULL)", name=op.f('ck_asset_indicators_ema50_value_state')),
    sa.CheckConstraint("ema200_state IN ('AVAILABLE','WARMUP','UNAVAILABLE','GAP_BLOCKED')", name=op.f('ck_asset_indicators_ema200_state')),
    sa.CheckConstraint("ema20_state IN ('AVAILABLE','WARMUP','UNAVAILABLE','GAP_BLOCKED')", name=op.f('ck_asset_indicators_ema20_state')),
    sa.CheckConstraint("ema50_state IN ('AVAILABLE','WARMUP','UNAVAILABLE','GAP_BLOCKED')", name=op.f('ck_asset_indicators_ema50_state')),
    sa.CheckConstraint("timeframe IN ('4h','1d','1w')", name=op.f('ck_asset_indicators_timeframe')),
    sa.CheckConstraint('consecutive_count >= 0', name=op.f('ck_asset_indicators_consecutive_count')),
    sa.ForeignKeyConstraint(['asset_id'], ['breadth_v2.assets.asset_id'], name=op.f('fk_asset_indicators_asset_id_assets')),
    sa.ForeignKeyConstraint(['candle_id'], ['breadth_v2.canonical_candles.candle_id'], name=op.f('fk_asset_indicators_candle_id_canonical_candles')),
    sa.ForeignKeyConstraint(['mapping_id', 'asset_id'], ['breadth_v2.provider_mappings.mapping_id', 'breadth_v2.provider_mappings.asset_id'], name=op.f('fk_asset_indicators_mapping_id_provider_mappings')),
    sa.ForeignKeyConstraint(['run_id'], ['breadth_v2.ingestion_runs.run_id'], name=op.f('fk_asset_indicators_run_id_ingestion_runs')),
    sa.ForeignKeyConstraint(['series_version'], ['breadth_v2.series_definitions.series_version'], name=op.f('fk_asset_indicators_series_version_series_definitions')),
    sa.ForeignKeyConstraint(['universe_version'], ['breadth_v2.universe_versions.universe_version'], name=op.f('fk_asset_indicators_universe_version_universe_versions')),
    sa.PrimaryKeyConstraint('series_version', 'asset_id', 'timeframe', 'candle_time', name=op.f('pk_asset_indicators')),
    schema='breadth_v2'
    )
    op.create_table('scanner_state',
    sa.Column('series_version', sa.String(length=120), nullable=False),
    sa.Column('timeframe', sa.String(length=4), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('candle_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('ema20', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('ema50', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('ema200', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('state20', sa.String(length=16), nullable=False),
    sa.Column('state50', sa.String(length=16), nullable=False),
    sa.Column('state200', sa.String(length=16), nullable=False),
    sa.Column('included_in_breadth', sa.Boolean(), nullable=False),
    sa.Column('mapping_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(state20 = 'UNAVAILABLE') = (ema20 IS NULL)", name=op.f('ck_scanner_state_state20_value')),
    sa.CheckConstraint("(state200 = 'UNAVAILABLE') = (ema200 IS NULL)", name=op.f('ck_scanner_state_state200_value')),
    sa.CheckConstraint("(state50 = 'UNAVAILABLE') = (ema50 IS NULL)", name=op.f('ck_scanner_state_state50_value')),
    sa.CheckConstraint("state20 IN ('ABOVE','BELOW','UNAVAILABLE')", name=op.f('ck_scanner_state_state20')),
    sa.CheckConstraint("state200 IN ('ABOVE','BELOW','UNAVAILABLE')", name=op.f('ck_scanner_state_state200')),
    sa.CheckConstraint("state50 IN ('ABOVE','BELOW','UNAVAILABLE')", name=op.f('ck_scanner_state_state50')),
    sa.CheckConstraint("timeframe IN ('4h','1d','1w')", name=op.f('ck_scanner_state_timeframe')),
    sa.ForeignKeyConstraint(['asset_id'], ['breadth_v2.assets.asset_id'], name=op.f('fk_scanner_state_asset_id_assets')),
    sa.ForeignKeyConstraint(['mapping_id', 'asset_id', 'source_id'], ['breadth_v2.provider_mappings.mapping_id', 'breadth_v2.provider_mappings.asset_id', 'breadth_v2.provider_mappings.source_id'], name=op.f('fk_scanner_state_mapping_id_provider_mappings')),
    sa.ForeignKeyConstraint(['series_version'], ['breadth_v2.series_definitions.series_version'], name=op.f('fk_scanner_state_series_version_series_definitions')),
    sa.ForeignKeyConstraint(['snapshot_id'], ['breadth_v2.breadth_snapshots.snapshot_id'], name=op.f('fk_scanner_state_snapshot_id_breadth_snapshots'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('series_version', 'timeframe', 'asset_id', name=op.f('pk_scanner_state')),
    schema='breadth_v2'
    )
    op.create_table('snapshot_members',
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('mapping_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('close', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('ema20', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('ema50', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('ema200', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('above20', sa.Boolean(), nullable=True),
    sa.Column('above50', sa.Boolean(), nullable=True),
    sa.Column('above200', sa.Boolean(), nullable=True),
    sa.Column('state20', sa.String(length=16), nullable=False),
    sa.Column('state50', sa.String(length=16), nullable=False),
    sa.Column('state200', sa.String(length=16), nullable=False),
    sa.Column('included_in_denominator', sa.Boolean(), nullable=False),
    sa.Column('exclusion_reason', sa.String(length=100), nullable=True),
    sa.CheckConstraint("(state20 = 'ABOVE' AND above20 IS TRUE) OR (state20 = 'BELOW' AND above20 IS FALSE) OR (state20 = 'UNAVAILABLE' AND above20 IS NULL)", name=op.f('ck_snapshot_members_state20_boolean')),
    sa.CheckConstraint("(state200 = 'ABOVE' AND above200 IS TRUE) OR (state200 = 'BELOW' AND above200 IS FALSE) OR (state200 = 'UNAVAILABLE' AND above200 IS NULL)", name=op.f('ck_snapshot_members_state200_boolean')),
    sa.CheckConstraint("(state50 = 'ABOVE' AND above50 IS TRUE) OR (state50 = 'BELOW' AND above50 IS FALSE) OR (state50 = 'UNAVAILABLE' AND above50 IS NULL)", name=op.f('ck_snapshot_members_state50_boolean')),
    sa.CheckConstraint("state20 IN ('ABOVE','BELOW','UNAVAILABLE')", name=op.f('ck_snapshot_members_state20')),
    sa.CheckConstraint("state200 IN ('ABOVE','BELOW','UNAVAILABLE')", name=op.f('ck_snapshot_members_state200')),
    sa.CheckConstraint("state50 IN ('ABOVE','BELOW','UNAVAILABLE')", name=op.f('ck_snapshot_members_state50')),
    sa.ForeignKeyConstraint(['asset_id'], ['breadth_v2.assets.asset_id'], name=op.f('fk_snapshot_members_asset_id_assets')),
    sa.ForeignKeyConstraint(['mapping_id', 'asset_id', 'source_id'], ['breadth_v2.provider_mappings.mapping_id', 'breadth_v2.provider_mappings.asset_id', 'breadth_v2.provider_mappings.source_id'], name=op.f('fk_snapshot_members_mapping_id_provider_mappings')),
    sa.ForeignKeyConstraint(['snapshot_id'], ['breadth_v2.breadth_snapshots.snapshot_id'], name=op.f('fk_snapshot_members_snapshot_id_breadth_snapshots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id', 'asset_id', name=op.f('pk_snapshot_members')),
    schema='breadth_v2'
    )
    op.execute("""
        CREATE FUNCTION breadth_v2.reject_immutable_change()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RAISE EXCEPTION 'immutable breadth_v2 relation: %', TG_TABLE_NAME
                USING ERRCODE = '55000';
        END;
        $$
    """)
    immutable_tables = (
        'source_versions',
        'provider_mappings',
        'universe_versions',
        'universe_memberships',
        'source_policy_versions',
        'source_policy_mappings',
        'series_definitions',
        'timeframe_cohorts',
        'source_artifacts',
        'canonical_candles',
        'asset_indicators',
        'breadth_snapshots',
        'snapshot_members',
    )
    for table_name in immutable_tables:
        op.execute(f"""
            CREATE TRIGGER trg_{table_name}_immutable
            BEFORE UPDATE OR DELETE ON breadth_v2.{table_name}
            FOR EACH ROW EXECUTE FUNCTION breadth_v2.reject_immutable_change()
        """)
    op.execute("""
        CREATE TRIGGER trg_assets_identity_immutable
        BEFORE UPDATE OF asset_id, canonical_id, symbol, metadata_id
        OR DELETE ON breadth_v2.assets
        FOR EACH ROW EXECUTE FUNCTION breadth_v2.reject_immutable_change()
    """)
    op.execute("""
        CREATE TRIGGER trg_data_sources_identity_immutable
        BEFORE UPDATE OF source_id, provider, venue, market_type
        OR DELETE ON breadth_v2.data_sources
        FOR EACH ROW EXECUTE FUNCTION breadth_v2.reject_immutable_change()
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TRIGGER trg_data_sources_identity_immutable ON breadth_v2.data_sources')
    op.execute('DROP TRIGGER trg_assets_identity_immutable ON breadth_v2.assets')
    for table_name in (
        'snapshot_members',
        'breadth_snapshots',
        'asset_indicators',
        'canonical_candles',
        'source_artifacts',
        'timeframe_cohorts',
        'series_definitions',
        'source_policy_mappings',
        'source_policy_versions',
        'universe_memberships',
        'universe_versions',
        'provider_mappings',
        'source_versions',
    ):
        op.execute(f'DROP TRIGGER trg_{table_name}_immutable ON breadth_v2.{table_name}')
    op.drop_table('snapshot_members', schema='breadth_v2')
    op.drop_table('scanner_state', schema='breadth_v2')
    op.drop_table('asset_indicators', schema='breadth_v2')
    op.drop_table('source_artifacts', schema='breadth_v2')
    op.drop_table('ingestion_errors', schema='breadth_v2')
    op.drop_index('ix_canonical_candles_asset_time', table_name='canonical_candles', schema='breadth_v2')
    op.drop_table('canonical_candles', schema='breadth_v2')
    op.drop_index('ix_breadth_snapshots_lookup', table_name='breadth_snapshots', schema='breadth_v2')
    op.drop_table('breadth_snapshots', schema='breadth_v2')
    op.drop_table('timeframe_cohorts', schema='breadth_v2')
    op.drop_table('source_policy_mappings', schema='breadth_v2')
    op.drop_table('ingestion_runs', schema='breadth_v2')
    op.drop_table('universe_memberships', schema='breadth_v2')
    op.drop_table('source_versions', schema='breadth_v2')
    op.drop_table('series_definitions', schema='breadth_v2')
    op.drop_table('provider_mappings', schema='breadth_v2')
    op.drop_table('universe_versions', schema='breadth_v2')
    op.drop_table('source_policy_versions', schema='breadth_v2')
    op.drop_table('data_sources', schema='breadth_v2')
    op.drop_table('assets', schema='breadth_v2')
    op.execute('DROP FUNCTION breadth_v2.reject_immutable_change()')
    # ### end Alembic commands ###
